// create stream
CREATE
    STREAM IF NOT EXISTS WIKI_EDITS_STREAM (
    TYPE STRING,
    `NAMESPACE` INTEGER,
    TITLE STRING,
    TITLEURL STRING,
    USER STRING,
    BOT BOOLEAN
) WITH (
    KAFKA_TOPIC='wiki_events',
    VALUE_FORMAT='JSON'
);

// create table by hopping windown
CREATE TABLE IF NOT EXISTS WIKI_EDITS_COUNT_HW WITH (
    KAFKA_TOPIC = 'WIKI_EDITS_COUNT_HW',
    VALUE_FORMAT = 'JSON',
    PARTITIONS = 3,
    REPLICAS = 1
) AS
SELECT
    TITLE
    , COUNT(*) AS EDITS_COUNT
    FROM WIKI_EDITS_STREAM WINDOW HOPPING (SIZE 30 MINUTES, ADVANCE BY 10 MINUTE)
    WHERE TYPE = 'edit' AND BOT = false
    GROUP BY TITLE
EMIT CHANGES;